Зотов Роман Алексеевич 6132
<br>Тема лабораторной работы: pandas

In [1]:
import pandas as pd
import numpy as np

# Задание 1
Считать в pandas.DataFrame любой источник данных: CSV, JSON, Excel-файл, HTML-таблицу и т.п. Также можно сконвертировать в DataFrame любой из встроенных датасетов sklearn

In [46]:
df = pd.read_json("pro_matches.json")
df

,match_id,duration,start_time,radiant_team_id,radiant_name,dire_team_id,dire_name,leagueid,league_name,series_id,series_type,radiant_score,dire_score,radiant_win,version
0,8229864824,1922,2025-03-26 12:45:57,8629318.0,Mad Monkeys,8629324.0,Swift Knights,17233,Destiny League,961523,1,29,41,False,22.0
1,8229844726,2238,2025-03-26 12:28:23,9651831.0,Eуе Gaming,9530867.0,Prodigy of God,17366,Ultras Dota Pro League 2024-25,961527,1,27,47,False,22.0
2,8229824447,2856,2025-03-26 12:17:34,7732977.0,BOOM Esports,9247354.0,Team Falcons,17907,FISSURE Universe Episode 4,961513,1,16,30,False,22.0
3,8229817205,2577,2025-03-26 12:05:24,8831040.0,Ghost Sheep,9593609.0,Nethercore,17366,Ultras Dota Pro League 2024-25,961514,1,38,37,False,22.0
4,8229815793,1415,2025-03-26 12:04:18,9330485.0,BulletProofs,8893837.0,Parallel eSports,16325,Ancients League,961516,1,35,25,True,22.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,8210774204,1997,2025-03-12 10:32:35,9303484.0,HEROIC,9247354.0,Team Falcons,17891,PGL Wallachia 2025 Season 3,956976,1,8,28,False,22.0
996,8210765191,951,2025-03-12 10:12:17,8629324.0,Swift Knights,8629005.0,Flawless Goblins,17233,Destiny League,956970,1,11,45,False,22.0
997,8210735241,2057,2025-03-12 09:31:39,9332069.0,Mister Maniacs,9330492.0,Iconic,16325,Ancients League,956971,1,27,37,False,22.0
998,8210732590,2832,2025-03-12 09:27:35,9640697.0,Eye Gaming,9593609.0,Nethercore,17366,Ultras Dota Pro League 2024-25,956966,1,40,53,False,22.0
999,8210731912,2119,2025-03-12 09:28:14,9467224.0,Aurora Gaming,9651814.0,Yellow Submarine,17891,PGL Wallachia 2025 Season 3,956962,1,26,22,True,22.0

In [47]:
print(df.columns)

Index(['match_id', 'duration', 'start_time', 'radiant_team_id', 'radiant_name',
       'dire_team_id', 'dire_name', 'leagueid', 'league_name', 'series_id',
       'series_type', 'radiant_score', 'dire_score', 'radiant_win', 'version'],
      dtype='object')

# Задание 2

<br>Датасет описывает профессиональные матчи в игре Дота 2
| Признак                     | Описание                                                                 | Единицы измерения     |
|-----------------------------|--------------------------------------------------------------------------|-----------------------|
|match_id | id матча | число | 
|duration | продолжительность матча | секунды |
|start_time | время начала матча |отчет времени|
|radiant_team_id | id команды света | число |
|radiant_name | название команды света ||
|dire_team_id | id команды тьмы ||
|dire_name | название команды тьмы ||
|leagueid | id соревнования ||
|series_id | id матча в соревновании ||
|league_name | название турнира ||
|series_type | тип серии матча (бо2, бо3 и т.д.) ||
|radiant_score | фентези поинт света |число|
|dire_score | фентези поинт тьмы |число|
|radiant_win | чья победа | True or False|
|version | ? ||

# Задание 3

In [3]:
df.head()

,match_id,duration,start_time,radiant_team_id,radiant_name,dire_team_id,dire_name,leagueid,league_name,series_id,series_type,radiant_score,dire_score,radiant_win,version
0,8229864824,1922,2025-03-26 12:45:57,8629318.0,Mad Monkeys,8629324.0,Swift Knights,17233,Destiny League,961523,1,29,41,False,22.0
1,8229844726,2238,2025-03-26 12:28:23,9651831.0,Eуе Gaming,9530867.0,Prodigy of God,17366,Ultras Dota Pro League 2024-25,961527,1,27,47,False,22.0
2,8229824447,2856,2025-03-26 12:17:34,7732977.0,BOOM Esports,9247354.0,Team Falcons,17907,FISSURE Universe Episode 4,961513,1,16,30,False,22.0
3,8229817205,2577,2025-03-26 12:05:24,8831040.0,Ghost Sheep,9593609.0,Nethercore,17366,Ultras Dota Pro League 2024-25,961514,1,38,37,False,22.0
4,8229815793,1415,2025-03-26 12:04:18,9330485.0,BulletProofs,8893837.0,Parallel eSports,16325,Ancients League,961516,1,35,25,True,22.0

In [4]:
df.describe()

,match_id,duration,start_time,radiant_team_id,dire_team_id,leagueid,series_id,series_type,radiant_score,dire_score,version
count,1.000000e+03,1000.000000,1000,9.370000e+02,9.400000e+02,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,999.0
mean,8.220882e+09,1977.562000,2025-03-19 19:43:55.444999936,8.866845e+06,8.960103e+06,17322.589000,889288.597000,0.896000,30.338000,29.880000,22.0
min,8.210732e+09,421.000000,2025-03-12 09:27:35,3.600000e+01,3.600000e+01,16251.000000,0.000000,0.000000,1.000000,2.000000,22.0
25%,8.216462e+09,1605.000000,2025-03-16 11:29:33.500000,8.629324e+06,8.807685e+06,17233.000000,957929.500000,1.000000,21.000000,20.000000,22.0
50%,8.221302e+09,1870.000000,2025-03-20 04:33:15,9.330485e+06,9.330489e+06,17366.000000,959230.000000,1.000000,31.000000,29.000000,22.0
75%,8.226028e+09,2236.250000,2025-03-23 13:23:09,9.587203e+06,9.593609e+06,17508.000000,960471.000000,1.000000,39.000000,39.000000,22.0
max,8.229865e+09,4530.000000,2025-03-26 12:45:57,9.723353e+06,9.723353e+06,17914.000000,961527.000000,3.000000,78.000000,78.000000,22.0
std,5.632785e+06,552.419987,NaN,1.537963e+06,1.340038e+06,428.148768,249683.645545,0.370569,12.461101,12.776339,0.0

In [5]:
#Считывание значения конкретной ячейки (с конкретным индексом из конкретной колонки).
df['radiant_name'][0]

'Mad Monkeys'

In [6]:
#Считывание значения конкретной ячейки (с конкретным индексом из конкретной колонки).
df.loc[0, 'radiant_name']

'Mad Monkeys'

In [7]:
#Фильтрация строк по диапазону индекса.
df[10:20]

,match_id,duration,start_time,radiant_team_id,radiant_name,dire_team_id,dire_name,leagueid,league_name,series_id,series_type,radiant_score,dire_score,radiant_win,version
10,8229755931,1906,2025-03-26 11:06:12,2443375.0,Foxy gaming,8629315.0,Wiser Warriors,17233,Destiny League,961518,1,25,36,False,22.0
11,8229753953,2079,2025-03-26 11:14:04,7732977.0,BOOM Esports,9247354.0,Team Falcons,17907,FISSURE Universe Episode 4,961513,1,11,20,False,22.0
12,8229726705,1297,2025-03-26 10:32:21,9587203.0,business club,9710379.0,Rakuzan,17366,Ultras Dota Pro League 2024-25,961509,1,26,13,True,22.0
13,8229725594,844,2025-03-26 10:32:10,9426115.0,Dark Rebellion,8629324.0,Swift Knights,17233,Destiny League,961510,1,5,32,False,22.0
14,8229723276,1939,2025-03-26 10:29:14,9330485.0,BulletProofs,8893837.0,Parallel eSports,16325,Ancients League,961516,1,28,26,False,22.0
15,8229716389,2036,2025-03-26 10:20:19,9593609.0,Nethercore,8831040.0,Ghost Sheep,17366,Ultras Dota Pro League 2024-25,961514,1,46,22,True,22.0
16,8229696317,2623,2025-03-26 10:00:10,7732977.0,BOOM Esports,9247354.0,Team Falcons,17907,FISSURE Universe Episode 4,961513,1,30,12,True,22.0
17,8229681928,1958,2025-03-26 09:38:30,8936507.0,FenixTeam,8893840.0,Big Bang Gaming,16325,Ancients League,961498,1,22,32,False,22.0
18,8229680764,1629,2025-03-26 09:42:44,8629324.0,Swift Knights,9426115.0,Dark Rebellion,17233,Destiny League,961510,1,37,21,True,22.0
19,8229677367,2518,2025-03-26 09:33:07,9710379.0,Rakuzan,9587203.0,business club,17366,Ultras Dota Pro League 2024-25,961509,1,62,56,True,22.0

In [8]:
#Фильтрация строк по диапазону индекса.
df.loc[10:20]

,match_id,duration,start_time,radiant_team_id,radiant_name,dire_team_id,dire_name,leagueid,league_name,series_id,series_type,radiant_score,dire_score,radiant_win,version
10,8229755931,1906,2025-03-26 11:06:12,2443375.0,Foxy gaming,8629315.0,Wiser Warriors,17233,Destiny League,961518,1,25,36,False,22.0
11,8229753953,2079,2025-03-26 11:14:04,7732977.0,BOOM Esports,9247354.0,Team Falcons,17907,FISSURE Universe Episode 4,961513,1,11,20,False,22.0
12,8229726705,1297,2025-03-26 10:32:21,9587203.0,business club,9710379.0,Rakuzan,17366,Ultras Dota Pro League 2024-25,961509,1,26,13,True,22.0
13,8229725594,844,2025-03-26 10:32:10,9426115.0,Dark Rebellion,8629324.0,Swift Knights,17233,Destiny League,961510,1,5,32,False,22.0
14,8229723276,1939,2025-03-26 10:29:14,9330485.0,BulletProofs,8893837.0,Parallel eSports,16325,Ancients League,961516,1,28,26,False,22.0
15,8229716389,2036,2025-03-26 10:20:19,9593609.0,Nethercore,8831040.0,Ghost Sheep,17366,Ultras Dota Pro League 2024-25,961514,1,46,22,True,22.0
16,8229696317,2623,2025-03-26 10:00:10,7732977.0,BOOM Esports,9247354.0,Team Falcons,17907,FISSURE Universe Episode 4,961513,1,30,12,True,22.0
17,8229681928,1958,2025-03-26 09:38:30,8936507.0,FenixTeam,8893840.0,Big Bang Gaming,16325,Ancients League,961498,1,22,32,False,22.0
18,8229680764,1629,2025-03-26 09:42:44,8629324.0,Swift Knights,9426115.0,Dark Rebellion,17233,Destiny League,961510,1,37,21,True,22.0
19,8229677367,2518,2025-03-26 09:33:07,9710379.0,Rakuzan,9587203.0,business club,17366,Ultras Dota Pro League 2024-25,961509,1,62,56,True,22.0
20,8229646764,1841,2025-03-26 08:53:01,8893840.0,Big Bang Gaming,8936507.0,FenixTeam,16325,Ancients League,961498,1,13,29,False,22.0

In [9]:
#Фильтрация набора данных по какому-либо условию.
df[df['radiant_win']]

,match_id,duration,start_time,radiant_team_id,radiant_name,dire_team_id,dire_name,leagueid,league_name,series_id,series_type,radiant_score,dire_score,radiant_win,version
4,8229815793,1415,2025-03-26 12:04:18,9330485.0,BulletProofs,8893837.0,Parallel eSports,16325,Ancients League,961516,1,35,25,True,22.0
5,8229815127,1789,2025-03-26 12:03:32,8629324.0,Swift Knights,8629318.0,Mad Monkeys,17233,Destiny League,961523,1,25,25,True,22.0
6,8229800493,1556,2025-03-26 11:50:48,8629315.0,Wiser Warriors,2443375.0,Foxy gaming,17233,Destiny League,961520,1,41,26,True,22.0
8,8229763128,2102,2025-03-26 11:12:45,8831040.0,Ghost Sheep,9593609.0,Nethercore,17366,Ultras Dota Pro League 2024-25,961514,1,47,32,True,22.0
12,8229726705,1297,2025-03-26 10:32:21,9587203.0,business club,9710379.0,Rakuzan,17366,Ultras Dota Pro League 2024-25,961509,1,26,13,True,22.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
978,8211002216,1865,2025-03-12 13:40:33,9530716.0,Air Defence,8831040.0,Ghost Sheep,17366,Ultras Dota Pro League 2024-25,957015,1,32,27,True,22.0
980,8210962162,1382,2025-03-12 13:09:59,9691942.0,Nethercore,9622167.0,Teiko,17366,Ultras Dota Pro League 2024-25,957007,1,43,12,True,22.0
985,8210893188,1247,2025-03-12 12:18:49,9332059.0,Ninja Bros,8893825.0,Lucky Bulldogs,16325,Ancients League,956984,1,36,12,True,22.0
991,8210826373,2514,2025-03-12 11:18:15,9505239.0,Rakuzan,8831040.0,Ghost Sheep,17366,Ultras Dota Pro League 2024-25,956982,1,51,31,True,22.0
999,8210731912,2119,2025-03-12 09:28:14,9467224.0,Aurora Gaming,9651814.0,Yellow Submarine,17891,PGL Wallachia 2025 Season 3,956962,1,26,22,True,22.0

In [10]:
#датасет с NaN
rows_with_na = df[df.isna().any(axis=1)]
rows_with_na

,match_id,duration,start_time,radiant_team_id,radiant_name,dire_team_id,dire_name,leagueid,league_name,series_id,series_type,radiant_score,dire_score,radiant_win,version
60,8228944728,1987,2025-03-25 16:48:38,NaN,None,NaN,None,17508,互联网联赛,0,0,20,45,False,22.0
61,8228882126,2557,2025-03-25 15:59:29,NaN,None,NaN,None,17508,互联网联赛,0,0,30,37,False,22.0
64,8228832636,707,2025-03-25 15:22:41,NaN,None,NaN,None,17508,互联网联赛,0,0,7,22,False,22.0
129,8227824156,2560,2025-03-24 18:56:29,NaN,None,NaN,None,17852,Eternal DOTA League Season 1,0,0,48,38,True,22.0
131,8227804471,3035,2025-03-24 18:39:51,NaN,None,NaN,None,17852,Eternal DOTA League Season 1,0,0,38,38,False,22.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
910,8212360496,1963,2025-03-13 14:36:36,NaN,None,NaN,None,17508,互联网联赛,0,0,33,21,True,22.0
914,8212310223,1348,2025-03-13 14:02:22,NaN,None,NaN,None,17508,互联网联赛,0,0,12,26,False,22.0
964,8211308265,3216,2025-03-12 17:15:20,NaN,None,NaN,None,17508,互联网联赛,0,0,58,48,True,22.0
967,8211239032,2337,2025-03-12 16:22:49,NaN,None,NaN,None,17508,互联网联赛,0,0,41,40,False,22.0
969,8211173896,2023,2025-03-12 15:35:44,NaN,None,NaN,None,17508,互联网联赛,0,0,32,55,False,22.0

In [11]:
#удаление строк с пропущенными значениями;
df_cleaned = df.dropna()
df_cleaned

,match_id,duration,start_time,radiant_team_id,radiant_name,dire_team_id,dire_name,leagueid,league_name,series_id,series_type,radiant_score,dire_score,radiant_win,version
0,8229864824,1922,2025-03-26 12:45:57,8629318.0,Mad Monkeys,8629324.0,Swift Knights,17233,Destiny League,961523,1,29,41,False,22.0
1,8229844726,2238,2025-03-26 12:28:23,9651831.0,Eуе Gaming,9530867.0,Prodigy of God,17366,Ultras Dota Pro League 2024-25,961527,1,27,47,False,22.0
2,8229824447,2856,2025-03-26 12:17:34,7732977.0,BOOM Esports,9247354.0,Team Falcons,17907,FISSURE Universe Episode 4,961513,1,16,30,False,22.0
3,8229817205,2577,2025-03-26 12:05:24,8831040.0,Ghost Sheep,9593609.0,Nethercore,17366,Ultras Dota Pro League 2024-25,961514,1,38,37,False,22.0
4,8229815793,1415,2025-03-26 12:04:18,9330485.0,BulletProofs,8893837.0,Parallel eSports,16325,Ancients League,961516,1,35,25,True,22.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,8210774204,1997,2025-03-12 10:32:35,9303484.0,HEROIC,9247354.0,Team Falcons,17891,PGL Wallachia 2025 Season 3,956976,1,8,28,False,22.0
996,8210765191,951,2025-03-12 10:12:17,8629324.0,Swift Knights,8629005.0,Flawless Goblins,17233,Destiny League,956970,1,11,45,False,22.0
997,8210735241,2057,2025-03-12 09:31:39,9332069.0,Mister Maniacs,9330492.0,Iconic,16325,Ancients League,956971,1,27,37,False,22.0
998,8210732590,2832,2025-03-12 09:27:35,9640697.0,Eye Gaming,9593609.0,Nethercore,17366,Ultras Dota Pro League 2024-25,956966,1,40,53,False,22.0
999,8210731912,2119,2025-03-12 09:28:14,9467224.0,Aurora Gaming,9651814.0,Yellow Submarine,17891,PGL Wallachia 2025 Season 3,956962,1,26,22,True,22.0

In [12]:
#заполнение пропущенных значений средним значением по колонке.
#не коректно конечно вставлять среднее но все же
column_name = ['radiant_team_id', 'dire_team_id']
means = df[column_name].mean()  # Вычисляем средние значения для колонок
df[column_name] = df[column_name].fillna(means)
df[df.isna().any(axis=1)]

,match_id,duration,start_time,radiant_team_id,radiant_name,dire_team_id,dire_name,leagueid,league_name,series_id,series_type,radiant_score,dire_score,radiant_win,version
60,8228944728,1987,2025-03-25 16:48:38,8.866845e+06,None,8.960103e+06,None,17508,互联网联赛,0,0,20,45,False,22.0
61,8228882126,2557,2025-03-25 15:59:29,8.866845e+06,None,8.960103e+06,None,17508,互联网联赛,0,0,30,37,False,22.0
64,8228832636,707,2025-03-25 15:22:41,8.866845e+06,None,8.960103e+06,None,17508,互联网联赛,0,0,7,22,False,22.0
129,8227824156,2560,2025-03-24 18:56:29,8.866845e+06,None,8.960103e+06,None,17852,Eternal DOTA League Season 1,0,0,48,38,True,22.0
131,8227804471,3035,2025-03-24 18:39:51,8.866845e+06,None,8.960103e+06,None,17852,Eternal DOTA League Season 1,0,0,38,38,False,22.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
910,8212360496,1963,2025-03-13 14:36:36,8.866845e+06,None,8.960103e+06,None,17508,互联网联赛,0,0,33,21,True,22.0
914,8212310223,1348,2025-03-13 14:02:22,8.866845e+06,None,8.960103e+06,None,17508,互联网联赛,0,0,12,26,False,22.0
964,8211308265,3216,2025-03-12 17:15:20,8.866845e+06,None,8.960103e+06,None,17508,互联网联赛,0,0,58,48,True,22.0
967,8211239032,2337,2025-03-12 16:22:49,8.866845e+06,None,8.960103e+06,None,17508,互联网联赛,0,0,41,40,False,22.0
969,8211173896,2023,2025-03-12 15:35:44,8.866845e+06,None,8.960103e+06,None,17508,互联网联赛,0,0,32,55,False,22.0

In [13]:
#Создание нового поля, вычисленного на основе значений других полей:
#через выражение на базе имеющихся колонок;
df['radiant_score_per_second'] = df['radiant_score']/df['duration']
df

,match_id,duration,start_time,radiant_team_id,radiant_name,dire_team_id,dire_name,leagueid,league_name,series_id,series_type,radiant_score,dire_score,radiant_win,version,radiant_score_per_second
0,8229864824,1922,2025-03-26 12:45:57,8629318.0,Mad Monkeys,8629324.0,Swift Knights,17233,Destiny League,961523,1,29,41,False,22.0,0.015088
1,8229844726,2238,2025-03-26 12:28:23,9651831.0,Eуе Gaming,9530867.0,Prodigy of God,17366,Ultras Dota Pro League 2024-25,961527,1,27,47,False,22.0,0.012064
2,8229824447,2856,2025-03-26 12:17:34,7732977.0,BOOM Esports,9247354.0,Team Falcons,17907,FISSURE Universe Episode 4,961513,1,16,30,False,22.0,0.005602
3,8229817205,2577,2025-03-26 12:05:24,8831040.0,Ghost Sheep,9593609.0,Nethercore,17366,Ultras Dota Pro League 2024-25,961514,1,38,37,False,22.0,0.014746
4,8229815793,1415,2025-03-26 12:04:18,9330485.0,BulletProofs,8893837.0,Parallel eSports,16325,Ancients League,961516,1,35,25,True,22.0,0.024735
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,8210774204,1997,2025-03-12 10:32:35,9303484.0,HEROIC,9247354.0,Team Falcons,17891,PGL Wallachia 2025 Season 3,956976,1,8,28,False,22.0,0.004006
996,8210765191,951,2025-03-12 10:12:17,8629324.0,Swift Knights,8629005.0,Flawless Goblins,17233,Destiny League,956970,1,11,45,False,22.0,0.011567
997,8210735241,2057,2025-03-12 09:31:39,9332069.0,Mister Maniacs,9330492.0,Iconic,16325,Ancients League,956971,1,27,37,False,22.0,0.013126
998,8210732590,2832,2025-03-12 09:27:35,9640697.0,Eye Gaming,9593609.0,Nethercore,17366,Ultras Dota Pro League 2024-25,956966,1,40,53,False,22.0,0.014124
999,8210731912,2119,2025-03-12 09:28:14,9467224.0,Aurora Gaming,9651814.0,Yellow Submarine,17891,PGL Wallachia 2025 Season 3,956962,1,26,22,True,22.0,0.012270

In [14]:
#через DataFrame.apply;
def custom_function(row):
    return row['dire_score']/row['duration']
df['dire_score_per_second'] = df.apply(custom_function, axis=1)
df

,match_id,duration,start_time,radiant_team_id,radiant_name,dire_team_id,dire_name,leagueid,league_name,series_id,series_type,radiant_score,dire_score,radiant_win,version,radiant_score_per_second,dire_score_per_second
0,8229864824,1922,2025-03-26 12:45:57,8629318.0,Mad Monkeys,8629324.0,Swift Knights,17233,Destiny League,961523,1,29,41,False,22.0,0.015088,0.021332
1,8229844726,2238,2025-03-26 12:28:23,9651831.0,Eуе Gaming,9530867.0,Prodigy of God,17366,Ultras Dota Pro League 2024-25,961527,1,27,47,False,22.0,0.012064,0.021001
2,8229824447,2856,2025-03-26 12:17:34,7732977.0,BOOM Esports,9247354.0,Team Falcons,17907,FISSURE Universe Episode 4,961513,1,16,30,False,22.0,0.005602,0.010504
3,8229817205,2577,2025-03-26 12:05:24,8831040.0,Ghost Sheep,9593609.0,Nethercore,17366,Ultras Dota Pro League 2024-25,961514,1,38,37,False,22.0,0.014746,0.014358
4,8229815793,1415,2025-03-26 12:04:18,9330485.0,BulletProofs,8893837.0,Parallel eSports,16325,Ancients League,961516,1,35,25,True,22.0,0.024735,0.017668
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,8210774204,1997,2025-03-12 10:32:35,9303484.0,HEROIC,9247354.0,Team Falcons,17891,PGL Wallachia 2025 Season 3,956976,1,8,28,False,22.0,0.004006,0.014021
996,8210765191,951,2025-03-12 10:12:17,8629324.0,Swift Knights,8629005.0,Flawless Goblins,17233,Destiny League,956970,1,11,45,False,22.0,0.011567,0.047319
997,8210735241,2057,2025-03-12 09:31:39,9332069.0,Mister Maniacs,9330492.0,Iconic,16325,Ancients League,956971,1,27,37,False,22.0,0.013126,0.017987
998,8210732590,2832,2025-03-12 09:27:35,9640697.0,Eye Gaming,9593609.0,Nethercore,17366,Ultras Dota Pro League 2024-25,956966,1,40,53,False,22.0,0.014124,0.018715
999,8210731912,2119,2025-03-12 09:28:14,9467224.0,Aurora Gaming,9651814.0,Yellow Submarine,17891,PGL Wallachia 2025 Season 3,956962,1,26,22,True,22.0,0.012270,0.010382

In [15]:
#через Series.apply.
df['league_name_upper'] = df['league_name'].apply(lambda x: x.upper() if isinstance(x, str) else x)
df

,match_id,duration,start_time,radiant_team_id,radiant_name,dire_team_id,dire_name,leagueid,league_name,series_id,series_type,radiant_score,dire_score,radiant_win,version,radiant_score_per_second,dire_score_per_second,league_name_upper
0,8229864824,1922,2025-03-26 12:45:57,8629318.0,Mad Monkeys,8629324.0,Swift Knights,17233,Destiny League,961523,1,29,41,False,22.0,0.015088,0.021332,DESTINY LEAGUE
1,8229844726,2238,2025-03-26 12:28:23,9651831.0,Eуе Gaming,9530867.0,Prodigy of God,17366,Ultras Dota Pro League 2024-25,961527,1,27,47,False,22.0,0.012064,0.021001,ULTRAS DOTA PRO LEAGUE 2024-25
2,8229824447,2856,2025-03-26 12:17:34,7732977.0,BOOM Esports,9247354.0,Team Falcons,17907,FISSURE Universe Episode 4,961513,1,16,30,False,22.0,0.005602,0.010504,FISSURE UNIVERSE EPISODE 4
3,8229817205,2577,2025-03-26 12:05:24,8831040.0,Ghost Sheep,9593609.0,Nethercore,17366,Ultras Dota Pro League 2024-25,961514,1,38,37,False,22.0,0.014746,0.014358,ULTRAS DOTA PRO LEAGUE 2024-25
4,8229815793,1415,2025-03-26 12:04:18,9330485.0,BulletProofs,8893837.0,Parallel eSports,16325,Ancients League,961516,1,35,25,True,22.0,0.024735,0.017668,ANCIENTS LEAGUE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,8210774204,1997,2025-03-12 10:32:35,9303484.0,HEROIC,9247354.0,Team Falcons,17891,PGL Wallachia 2025 Season 3,956976,1,8,28,False,22.0,0.004006,0.014021,PGL WALLACHIA 2025 SEASON 3
996,8210765191,951,2025-03-12 10:12:17,8629324.0,Swift Knights,8629005.0,Flawless Goblins,17233,Destiny League,956970,1,11,45,False,22.0,0.011567,0.047319,DESTINY LEAGUE
997,8210735241,2057,2025-03-12 09:31:39,9332069.0,Mister Maniacs,9330492.0,Iconic,16325,Ancients League,956971,1,27,37,False,22.0,0.013126,0.017987,ANCIENTS LEAGUE
998,8210732590,2832,2025-03-12 09:27:35,9640697.0,Eye Gaming,9593609.0,Nethercore,17366,Ultras Dota Pro League 2024-25,956966,1,40,53,False,22.0,0.014124,0.018715,ULTRAS DOTA PRO LEAGUE 2024-25
999,8210731912,2119,2025-03-12 09:28:14,9467224.0,Aurora Gaming,9651814.0,Yellow Submarine,17891,PGL Wallachia 2025 Season 3,956962,1,26,22,True,22.0,0.012270,0.010382,PGL WALLACHIA 2025 SEASON 3

In [16]:
#Сортировка по какому-либо из полей.
df.sort_values(by='duration')

,match_id,duration,start_time,radiant_team_id,radiant_name,dire_team_id,dire_name,leagueid,league_name,series_id,series_type,radiant_score,dire_score,radiant_win,version,radiant_score_per_second,dire_score_per_second,league_name_upper
847,8213654766,421,2025-03-14 14:42:45,8.866845e+06,None,8.960103e+06,None,17508,互联网联赛,0,0,10,4,True,22.0,0.023753,0.009501,互联网联赛
64,8228832636,707,2025-03-25 15:22:41,8.866845e+06,None,8.960103e+06,None,17508,互联网联赛,0,0,7,22,False,22.0,0.009901,0.031117,互联网联赛
712,8216984800,833,2025-03-16 17:04:24,9.482900e+06,Рязань-ВДВ,9.685186e+06,LINYX,17909,WBT CYBER CLUB #1,958466,0,24,4,True,22.0,0.028812,0.004802,WBT CYBER CLUB #1
13,8229725594,844,2025-03-26 10:32:10,9.426115e+06,Dark Rebellion,8.629324e+06,Swift Knights,17233,Destiny League,961510,1,5,32,False,22.0,0.005924,0.037915,DESTINY LEAGUE
336,8224101667,894,2025-03-22 08:34:59,9.716135e+06,None,9.677513e+06,Excel Esports,17875,ACL×ESL Challenger China,960038,0,1,15,False,22.0,0.001119,0.016779,ACL×ESL CHALLENGER CHINA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
834,8214023491,4193,2025-03-14 19:15:37,9.247354e+06,Team Falcons,8.291895e+06,Tundra Esports,17891,PGL Wallachia 2025 Season 3,957770,1,46,20,True,22.0,0.010971,0.004770,PGL WALLACHIA 2025 SEASON 3
774,8215554627,4242,2025-03-15 19:16:12,9.652269e+06,PERRO NEGRO,9.710443e+06,AllStars,17367,EPL World Series: America 2024-2025 Season,958145,1,57,44,True,22.0,0.013437,0.010372,EPL WORLD SERIES: AMERICA 2024-2025 SEASON
804,8214704203,4474,2025-03-15 09:06:56,7.119388e+06,Team Spirit,8.261500e+06,Xtreme Gaming,17891,PGL Wallachia 2025 Season 3,957937,1,43,25,True,22.0,0.009611,0.005588,PGL WALLACHIA 2025 SEASON 3
389,8222947845,4495,2025-03-21 12:59:12,8.588969e+06,HYDRA,9.717032e+06,Eternal Academy,17381,European Pro League 2024-2025 Season,959726,1,52,52,False,22.0,0.011568,0.011568,EUROPEAN PRO LEAGUE 2024-2025 SEASON
784,8215196222,4530,2025-03-15 15:08:03,2.163000e+03,Team Liquid,9.247354e+06,Team Falcons,17891,PGL Wallachia 2025 Season 3,958030,1,37,34,True,22.0,0.008168,0.007506,PGL WALLACHIA 2025 SEASON 3

In [17]:
#Вычисление нескольких статистик по колонкам (использовать встроенные агрегатные функции - любые на выбор).
mean_value = df['duration'].mean()
max_value = df['duration'].max()
print(f"Среднее время игры: {mean_value}, Максимальное время игры: {max_value}")

Среднее время игры: 1977.562, Максимальное время игры: 4530

In [18]:
#Вывод по какому-либо полю / набору полей числа значений с использованием .value_counts().
df['radiant_win'].value_counts()

radiant_win
True     512
False    488
Name: count, dtype: int64

In [19]:
df['radiant_name'].unique()

array(['Mad Monkeys', 'Eуе Gaming', 'BOOM Esports', 'Ghost Sheep',
       'BulletProofs', 'Swift Knights', 'Wiser Warriors',
       'Parallel eSports', 'Rakuzan', 'Foxy gaming', 'business club',
       'Dark Rebellion', 'Nethercore', 'FenixTeam', 'Big Bang Gaming',
       'LSG', 'The MongolZ', 'Dragon Blood', 'Teiko', 'Lighting Legends',
       'Call911', 'Prodigy of God', 'Shadow Avengers', 'SHAOLIN',
       'Bright Crusaders', 'Hustlers', 'Lucky Bulldogs', 'Wild Dragon',
       'FALL VICTIMS', 'Estar Backs', 'Moonwalkers', 'REAL ECLIPSE',
       'PERRO NEGRO', 'HELLBEAR HEROES', 'Vitality Warriors',
       'Silent killer', 'TeamCompromiso', 'Night Vision', 'White Dragons',
       'Night Pulse', 'Team Liquid', 'KIBA ARMS', 'Dominion', None,
       'Team Tidebound', 'Aurora Gaming', 'Flawless Goblins',
       'Shinigami Gaming', 'PARIVISION', 'Wildcard', 'Marvelous Warriors',
       'Ninja Bros', 'Crew X', 'Tech Free Gaming', 'AllStars',
       'Lava Esports ', 'Tundra Esports', 'Progress Gaming',
       'Gaimin Gladiators', 'Team Falcons', 'Team Spirit', 'Talon',
       'One Move', 'ThunderLab', '1w Team', 'Groomify', 'RuleBreakers',
       'Iconic', 'Yangon Galacticos', 'Prodigy Of God', 'BetBoom Team',
       'барселона', 'Elite Eclipse', 'Kastrula team', 'Silent Shadows',
       'скрепыши', '5vpotoke', "5clown's", 'Falanga Gaming',
       'Excel Esports', 'Eye Gaming ', 'Pride', 'Рязань-ВДВ',
       'Air Defense', 'InterActive Philippines', '4Pirates', 'Team Lynx',
       'Eye Gaming', 'Zero Tenacity', 'No Magnus Team', 'END GAME',
       'Nemiga Gaming', 'HYDRA', 'Carstensz Esports', 'Dominatrix',
       'Eternal Academy', 'NGNB', 'Mister Maniacs', 'Raiders Gaming',
       'Titan Strikers', 'Apple City Gang', 'Passion UA', 'TEIKO',
       'EYE Gaming', 'Air Defence', 'Работяги', 'Ivory', 'EYE GAMING',
       'Клининг', 'night_wolves', 'GenerationZer-', 'TERA', 'SOSATELI',
       'Easy Gaming', '5vPotoke', 'N0brain', 'МГАФК-2',
       'Team spirit low iq', 'SIGIZMUNDI', 'Leto', 'WelcomeToRussia',
       'Team.Spectrum', 'HoG', 'Xtreme Gaming', 'Kiba Arms',
       'Natus Vincere', 'HEROIC'], dtype=object)

In [20]:
df = df.reset_index(drop=True)  # Удаляем текущий индекс
df = df.set_index('match_id')
df

,duration,start_time,radiant_team_id,radiant_name,dire_team_id,dire_name,leagueid,league_name,series_id,series_type,radiant_score,dire_score,radiant_win,version,radiant_score_per_second,dire_score_per_second,league_name_upper
match_id,,,,,,,,,,,,,,,,,
8229864824,1922,2025-03-26 12:45:57,8629318.0,Mad Monkeys,8629324.0,Swift Knights,17233,Destiny League,961523,1,29,41,False,22.0,0.015088,0.021332,DESTINY LEAGUE
8229844726,2238,2025-03-26 12:28:23,9651831.0,Eуе Gaming,9530867.0,Prodigy of God,17366,Ultras Dota Pro League 2024-25,961527,1,27,47,False,22.0,0.012064,0.021001,ULTRAS DOTA PRO LEAGUE 2024-25
8229824447,2856,2025-03-26 12:17:34,7732977.0,BOOM Esports,9247354.0,Team Falcons,17907,FISSURE Universe Episode 4,961513,1,16,30,False,22.0,0.005602,0.010504,FISSURE UNIVERSE EPISODE 4
8229817205,2577,2025-03-26 12:05:24,8831040.0,Ghost Sheep,9593609.0,Nethercore,17366,Ultras Dota Pro League 2024-25,961514,1,38,37,False,22.0,0.014746,0.014358,ULTRAS DOTA PRO LEAGUE 2024-25
8229815793,1415,2025-03-26 12:04:18,9330485.0,BulletProofs,8893837.0,Parallel eSports,16325,Ancients League,961516,1,35,25,True,22.0,0.024735,0.017668,ANCIENTS LEAGUE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8210774204,1997,2025-03-12 10:32:35,9303484.0,HEROIC,9247354.0,Team Falcons,17891,PGL Wallachia 2025 Season 3,956976,1,8,28,False,22.0,0.004006,0.014021,PGL WALLACHIA 2025 SEASON 3
8210765191,951,2025-03-12 10:12:17,8629324.0,Swift Knights,8629005.0,Flawless Goblins,17233,Destiny League,956970,1,11,45,False,22.0,0.011567,0.047319,DESTINY LEAGUE
8210735241,2057,2025-03-12 09:31:39,9332069.0,Mister Maniacs,9330492.0,Iconic,16325,Ancients League,956971,1,27,37,False,22.0,0.013126,0.017987,ANCIENTS LEAGUE
8210732590,2832,2025-03-12 09:27:35,9640697.0,Eye Gaming,9593609.0,Nethercore,17366,Ultras Dota Pro League 2024-25,956966,1,40,53,False,22.0,0.014124,0.018715,ULTRAS DOTA PRO LEAGUE 2024-25
8210731912,2119,2025-03-12 09:28:14,9467224.0,Aurora Gaming,9651814.0,Yellow Submarine,17891,PGL Wallachia 2025 Season 3,956962,1,26,22,True,22.0,0.012270,0.010382,PGL WALLACHIA 2025 SEASON 3

# Задание 4

In [ ]:
#Продемонстрировать работу .groupby, на основе группировок в groupby вычислить агрегатные функции по одной или нескольким колонкам.
df['sum_duration'] = df['duration']
df['avg_duration'] = df['duration']


grouped = df.groupby(['radiant_name','league_name']).agg({
    'sum_duration': 'sum',
    'avg_duration': 'mean'
}).reset_index()



grouped

,radiant_name,league_name,sum_duration,avg_duration
0,1w Team,FISSURE Universe Episode 4,16730,2390.0
1,4Pirates,European Pro League 2024-2025 Season,4295,2147.5
2,5clown's,SIVVIT League,1011,1011.0
3,5vPotoke,SIVVIT League,2024,2024.0
4,5vpotoke,Party To Play league,1949,1949.0
...,...,...,...,...
129,МГАФК-2,SIVVIT League,1015,1015.0
130,Работяги,European Pro League 2024-2025 Season,5026,2513.0
131,Рязань-ВДВ,WBT CYBER CLUB #1,2077,1038.5
132,барселона,WBT CYBER CLUB #1,2787,2787.0
133,скрепыши,SIVVIT League,3663,3663.0

# Задание 5

In [ ]:
#Решейпинг данных 1D→2D с использованием .pivot (можно подать на вход результаты агрегатов, полученных ранее с использованием .groupby (сгруппировать по двум полям).
pivoted = grouped.pivot(index='radiant_name',columns='league_name', values=['sum_duration', 'avg_duration'])
pivoted

                         sum_duration                              \
league_name  ACL×ESL Challenger China ANUBISS CUP Ancients League
radiant_name
1w Team                           NaN         NaN             NaN
4Pirates                          NaN         NaN             NaN
5clown's                          NaN         NaN             NaN
5vPotoke                          NaN         NaN             NaN
5vpotoke                          NaN         NaN             NaN
...                               ...         ...             ...
МГАФК-2                           NaN         NaN             NaN
Работяги                          NaN         NaN             NaN
Рязань-ВДВ                        NaN         NaN             NaN
барселона                         NaN         NaN             NaN
скрепыши                          NaN         NaN             NaN

                                                 \
league_name  Destiny League Dota 2 Space League
radiant_name
1w Team                 NaN                 NaN
4Pirates                NaN                 NaN
5clown's                NaN                 NaN
5vPotoke                NaN                 NaN
5vpotoke                NaN                 NaN
...                     ...                 ...
МГАФК-2                 NaN                 NaN
Работяги                NaN                 NaN
Рязань-ВДВ              NaN                 NaN
барселона               NaN                 NaN
скрепыши                NaN                 NaN

                                                          \
league_name  EPL World Series: America 2024-2025 Season
radiant_name
1w Team                                              NaN
4Pirates                                             NaN
5clown's                                             NaN
5vPotoke                                             NaN
5vpotoke                                             NaN
...                                                  ...
МГАФК-2                                              NaN
Работяги                                             NaN
Рязань-ВДВ                                           NaN
барселона                                            NaN
скрепыши                                             NaN

                                                                 \
league_name  EPL World Series: Southeast Asia 2024-2025 Season
radiant_name
1w Team                                                     NaN
4Pirates                                                    NaN
5clown's                                                    NaN
5vPotoke                                                    NaN
5vpotoke                                                    NaN
...                                                         ...
МГАФК-2                                                     NaN
Работяги                                                    NaN
Рязань-ВДВ                                                  NaN
барселона                                                   NaN
скрепыши                                                    NaN

                                           \
league_name  Eternal DOTA League Season 1
radiant_name
1w Team                               NaN
4Pirates                              NaN
5clown's                              NaN
5vPotoke                              NaN
5vpotoke                              NaN
...                                   ...
МГАФК-2                               NaN
Работяги                              NaN
Рязань-ВДВ                            NaN
барселона                             NaN
скрепыши                              NaN

                                                                               \
league_name  European Pro League  2024-2025 Season FISSURE Universe Episode 4
radiant_name
1w Team                                        NaN                    16730.0
4Pirates                                    4295.0                        NaN
5clown's                                       NaN                        NaN
5vPotoke                                       NaN                        NaN
5vpotoke                                       NaN                        NaN
...                                            ...                        ...
МГАФК-2                                        NaN                        NaN
Работяги                                    5026.0                        NaN
Рязань-ВДВ                                     NaN                        NaN
барселона                                      NaN                        NaN
скрепыши                                       NaN                        NaN

              ...                                avg_duration  \
league_name   ... EPL World Series: America 2024-2025 Season
radiant_name  ...
1w Team       ...                                         NaN
4Pirates      ...                                         NaN
5clown's      ...                                         NaN
5vPotoke      ...                                         NaN
5vpotoke      ...                                         NaN
...           ...                                         ...
МГАФК-2       ...                                         NaN
Работяги      ...                                         NaN
Рязань-ВДВ    ...                                         NaN
барселона     ...                                         NaN
скрепыши      ...                                         NaN

                                                                 \
league_name  EPL World Series: Southeast Asia 2024-2025 Season
radiant_name
1w Team                                                     NaN
4Pirates                                                    NaN
5clown's                                                    NaN
5vPotoke                                                    NaN
5vpotoke                                                    NaN
...                                                         ...
МГАФК-2                                                     NaN
Работяги                                                    NaN
Рязань-ВДВ                                                  NaN
барселона                                                   NaN
скрепыши                                                    NaN

                                           \
league_name  Eternal DOTA League Season 1
radiant_name
1w Team                               NaN
4Pirates                              NaN
5clown's                              NaN
5vPotoke                              NaN
5vpotoke                              NaN
...                                   ...
МГАФК-2                               NaN
Работяги                              NaN
Рязань-ВДВ                            NaN
барселона                             NaN
скрепыши                              NaN

                                                                               \
league_name  European Pro League  2024-2025 Season FISSURE Universe Episode 4
radiant_name
1w Team                                        NaN                     2390.0
4Pirates                                    2147.5                        NaN
5clown's                                       NaN                        NaN
5vPotoke                                       NaN                        NaN
5vpotoke                                       NaN                        NaN
...                                            ...                        ...
МГАФК-2                                        NaN                        NaN
Работяги                                    2513.0                        NaN
Рязань-ВДВ                                     NaN                        NaN
барселона                                      NaN                        NaN
скрепыши                                       NaN                        NaN

                                                                             \
league_name  PGL Wallachia 2025 Season 3 Party To Play league SIVVIT League
radiant_name
1w Team                              NaN                  NaN           NaN
4Pirates                             NaN                  NaN           NaN
5clown's                             NaN                  NaN        1011.0
5vPotoke                             NaN                  NaN        2024.0
5vpotoke                             NaN               1949.0        3839.0
...                                  ...                  ...           ...
МГАФК-2                              NaN                  NaN        1015.0
Работяги                             NaN                  NaN           NaN
Рязань-ВДВ                           NaN                  NaN           NaN
барселона                            NaN                  NaN           NaN
скрепыши                             NaN                  NaN        3663.0


league_name  Ultras Dota Pro League  2024-25 WBT CYBER CLUB #1
radiant_name
1w Team                                  NaN               NaN
4Pirates                                 NaN               NaN
5clown's                                 NaN               NaN
5vPotoke                                 NaN               NaN
5vpotoke                                 NaN               NaN
...                                      ...               ...
МГАФК-2                                  NaN               NaN
Работяги                                 NaN               NaN
Рязань-ВДВ                               NaN            1038.5
барселона                                NaN            2787.0
скрепыши                                 NaN               NaN

[126 rows x 30 columns]

# Задание 6

In [ ]:
#Решейпинг 1D→2D данных, соединённых с группировкой / агрегацией (одним словом - сводная таблица): .pivot_table. Группировать только по категориальным полям или числовым, если значений немного
pivot_table = df.pivot_table(
    index='radiant_name',
    columns='league_name',
    values=['avg_duration', 'sum_duration'],
    aggfunc={'avg_duration': 'mean','sum_duration': 'sum' }
)
pivot_table

                         avg_duration                              \
league_name  ACL×ESL Challenger China ANUBISS CUP Ancients League
radiant_name
1w Team                           NaN         NaN             NaN
4Pirates                          NaN         NaN             NaN
5clown's                          NaN         NaN             NaN
5vPotoke                          NaN         NaN             NaN
5vpotoke                          NaN         NaN             NaN
...                               ...         ...             ...
МГАФК-2                           NaN         NaN             NaN
Работяги                          NaN         NaN             NaN
Рязань-ВДВ                        NaN         NaN             NaN
барселона                         NaN         NaN             NaN
скрепыши                          NaN         NaN             NaN

                                                 \
league_name  Destiny League Dota 2 Space League
radiant_name
1w Team                 NaN                 NaN
4Pirates                NaN                 NaN
5clown's                NaN                 NaN
5vPotoke                NaN                 NaN
5vpotoke                NaN                 NaN
...                     ...                 ...
МГАФК-2                 NaN                 NaN
Работяги                NaN                 NaN
Рязань-ВДВ              NaN                 NaN
барселона               NaN                 NaN
скрепыши                NaN                 NaN

                                                          \
league_name  EPL World Series: America 2024-2025 Season
radiant_name
1w Team                                              NaN
4Pirates                                             NaN
5clown's                                             NaN
5vPotoke                                             NaN
5vpotoke                                             NaN
...                                                  ...
МГАФК-2                                              NaN
Работяги                                             NaN
Рязань-ВДВ                                           NaN
барселона                                            NaN
скрепыши                                             NaN

                                                                 \
league_name  EPL World Series: Southeast Asia 2024-2025 Season
radiant_name
1w Team                                                     NaN
4Pirates                                                    NaN
5clown's                                                    NaN
5vPotoke                                                    NaN
5vpotoke                                                    NaN
...                                                         ...
МГАФК-2                                                     NaN
Работяги                                                    NaN
Рязань-ВДВ                                                  NaN
барселона                                                   NaN
скрепыши                                                    NaN

                                           \
league_name  Eternal DOTA League Season 1
radiant_name
1w Team                               NaN
4Pirates                              NaN
5clown's                              NaN
5vPotoke                              NaN
5vpotoke                              NaN
...                                   ...
МГАФК-2                               NaN
Работяги                              NaN
Рязань-ВДВ                            NaN
барселона                             NaN
скрепыши                              NaN

                                                                               \
league_name  European Pro League  2024-2025 Season FISSURE Universe Episode 4
radiant_name
1w Team                                        NaN                     2390.0
4Pirates                                    2147.5                        NaN
5clown's                                       NaN                        NaN
5vPotoke                                       NaN                        NaN
5vpotoke                                       NaN                        NaN
...                                            ...                        ...
МГАФК-2                                        NaN                        NaN
Работяги                                    2513.0                        NaN
Рязань-ВДВ                                     NaN                        NaN
барселона                                      NaN                        NaN
скрепыши                                       NaN                        NaN

              ...                                sum_duration  \
league_name   ... EPL World Series: America 2024-2025 Season
radiant_name  ...
1w Team       ...                                         NaN
4Pirates      ...                                         NaN
5clown's      ...                                         NaN
5vPotoke      ...                                         NaN
5vpotoke      ...                                         NaN
...           ...                                         ...
МГАФК-2       ...                                         NaN
Работяги      ...                                         NaN
Рязань-ВДВ    ...                                         NaN
барселона     ...                                         NaN
скрепыши      ...                                         NaN

                                                                 \
league_name  EPL World Series: Southeast Asia 2024-2025 Season
radiant_name
1w Team                                                     NaN
4Pirates                                                    NaN
5clown's                                                    NaN
5vPotoke                                                    NaN
5vpotoke                                                    NaN
...                                                         ...
МГАФК-2                                                     NaN
Работяги                                                    NaN
Рязань-ВДВ                                                  NaN
барселона                                                   NaN
скрепыши                                                    NaN

                                           \
league_name  Eternal DOTA League Season 1
radiant_name
1w Team                               NaN
4Pirates                              NaN
5clown's                              NaN
5vPotoke                              NaN
5vpotoke                              NaN
...                                   ...
МГАФК-2                               NaN
Работяги                              NaN
Рязань-ВДВ                            NaN
барселона                             NaN
скрепыши                              NaN

                                                                               \
league_name  European Pro League  2024-2025 Season FISSURE Universe Episode 4
radiant_name
1w Team                                        NaN                    16730.0
4Pirates                                    4295.0                        NaN
5clown's                                       NaN                        NaN
5vPotoke                                       NaN                        NaN
5vpotoke                                       NaN                        NaN
...                                            ...                        ...
МГАФК-2                                        NaN                        NaN
Работяги                                    5026.0                        NaN
Рязань-ВДВ                                     NaN                        NaN
барселона                                      NaN                        NaN
скрепыши                                       NaN                        NaN

                                                                             \
league_name  PGL Wallachia 2025 Season 3 Party To Play league SIVVIT League
radiant_name
1w Team                              NaN                  NaN           NaN
4Pirates                             NaN                  NaN           NaN
5clown's                             NaN                  NaN        1011.0
5vPotoke                             NaN                  NaN        2024.0
5vpotoke                             NaN               1949.0        3839.0
...                                  ...                  ...           ...
МГАФК-2                              NaN                  NaN        1015.0
Работяги                             NaN                  NaN           NaN
Рязань-ВДВ                           NaN                  NaN           NaN
барселона                            NaN                  NaN           NaN
скрепыши                             NaN                  NaN        3663.0


league_name  Ultras Dota Pro League  2024-25 WBT CYBER CLUB #1
radiant_name
1w Team                                  NaN               NaN
4Pirates                                 NaN               NaN
5clown's                                 NaN               NaN
5vPotoke                                 NaN               NaN
5vpotoke                                 NaN               NaN
...                                      ...               ...
МГАФК-2                                  NaN               NaN
Работяги                                 NaN               NaN
Рязань-ВДВ                               NaN            2077.0
барселона                                NaN            2787.0
скрепыши                                 NaN               NaN

[126 rows x 30 columns]

# Задание 7

In [24]:
# Вычисление квантилей
q25 = np.quantile(grouped['avg_duration'], 0.25)  # 25-й квантиль
q50 = np.quantile(grouped['avg_duration'], 0.50)  # 50-й квантиль (медиана)
q75 = np.quantile(grouped['avg_duration'], 0.75)  # 75-й квантиль

# Вывод результатов
print(f"25-й квантиль: {q25}")
print(f"50-й квантиль (медиана): {q50}")
print(f"75-й квантиль: {q75}")

25-й квантиль: 1770.0681818181818
50-й квантиль (медиана): 2019.8333333333335
75-й квантиль: 2286.25

In [25]:
# Вычисление процентилей
p25 = np.percentile(grouped['avg_duration'], 25)
p50 = np.percentile(grouped['avg_duration'], 50)
p75 = np.percentile(grouped['avg_duration'], 75)

# Вывод результатов
print(f"25-й процентиль: {p25}")
print(f"50-й процентиль (медиана): {p50}")
print(f"75-й процентиль: {p75}")

25-й процентиль: 1770.0681818181818
50-й процентиль (медиана): 2019.8333333333335
75-й процентиль: 2286.25

# Задание 8

In [ ]:
#Вычислить (в виде текста) гистограмму какого-либо вещественного признака (с использованием numpy.histogram). 
# Значения гистограммы можно использовать в качестве загрубленного числового признака для заданий (5) или (6).
counts, bins = np.histogram(grouped['avg_duration'], bins=5)
grouped['price_bin'] = np.digitize(grouped['avg_duration'], bins)
grouped

,radiant_name,league_name,sum_duration,avg_duration,price_bin
0,1w Team,FISSURE Universe Episode 4,16730,2390.0,3
1,4Pirates,European Pro League 2024-2025 Season,4295,2147.5,3
2,5clown's,SIVVIT League,1011,1011.0,1
3,5vPotoke,SIVVIT League,2024,2024.0,2
4,5vpotoke,Party To Play league,1949,1949.0,2
...,...,...,...,...,...
129,МГАФК-2,SIVVIT League,1015,1015.0,1
130,Работяги,European Pro League 2024-2025 Season,5026,2513.0,3
131,Рязань-ВДВ,WBT CYBER CLUB #1,2077,1038.5,1
132,барселона,WBT CYBER CLUB #1,2787,2787.0,4
133,скрепыши,SIVVIT League,3663,3663.0,5

# Задание 9

In [ ]:
#Проитерировать DataFrame построчно .iterrows() и выполнить какую-либо операцию внутри цикла.
for index, row in df.iterrows():
    if row["radiant_win"]:
      print("Победа команды сил света")
    else:
      print("Победа команды сил тьмы")

Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил света
Победа команды сил тьмы
Победа команды сил света
Победа команды сил тьмы

# Задание 10

In [ ]:
#Получить DataFrame с MultiIndex любым способом: через конструктор (в документации есть множество видов конструкторов для создания MultiIndex с нуля), 
# через read_sql / read_csv / read_excel, read_*, через pivot_table, через groupby или иными способами.
np.random.seed(42)


n = 100
regions = np.random.choice(['North', 'South', 'East'], size=n)
products = np.random.choice(['Laptop', 'Phone', 'Tablet'], size=n)
sales = np.random.randint(1, 10, size=n)
prices = np.random.uniform(100, 1000, size=n)


df = pd.DataFrame({
    'region': regions,
    'product': products,
    'sales': sales,
    'price': prices
})

print("Исходный DataFrame:")
df

Исходный DataFrame:

   region product  sales       price
0    East  Tablet      4  313.524179
1   North  Tablet      1  392.859728
2    East  Tablet      1  771.842265
3    East  Laptop      4  684.669609
4   North  Tablet      7  864.301069
..    ...     ...    ...         ...
95  North   Phone      3  495.074279
96  North  Tablet      9  170.610743
97   East  Tablet      4  122.815669
98  North   Phone      1  966.383573
99  North  Laptop      4  852.382108

[100 rows x 4 columns]

In [29]:
multi_df = df.groupby(['region', 'product']).agg({
    'sales': 'sum',
    'price': 'mean'
})

multi_df

                sales       price
region product
East   Laptop      42  612.015332
       Phone       29  510.572273
       Tablet      68  642.106376
North  Laptop      45  636.751785
       Phone       24  679.160920
       Tablet      79  538.842805
South  Laptop      61  501.890337
       Phone       51  551.129229
       Tablet      56  579.716231

In [ ]:
#Переставить местами уровни индекса.
swapped_df = multi_df.swaplevel('region', 'product')
swapped_df.sort_index()
swapped_df

                sales       price
product region
Laptop  East       42  612.015332
Phone   East       29  510.572273
Tablet  East       68  642.106376
Laptop  North      45  636.751785
Phone   North      24  679.160920
Tablet  North      79  538.842805
Laptop  South      61  501.890337
Phone   South      51  551.129229
Tablet  South      56  579.716231

In [ ]:
#Транспонировать таблицу (или создать новую другую) с MultiIndex.
transposed_df = multi_df.T
transposed_df

region         East                               North             \
product      Laptop       Phone      Tablet      Laptop      Phone
sales     42.000000   29.000000   68.000000   45.000000   24.00000
price    612.015332  510.572273  642.106376  636.751785  679.16092

region                    South
product      Tablet      Laptop       Phone      Tablet
sales     79.000000   61.000000   51.000000   56.000000
price    538.842805  501.890337  551.129229  579.716231

In [ ]:
#Удалить один из уровней индекса или добавить новый уровень индекса (можно инициализированный константой) - см. документацию.
df_dropped = multi_df.droplevel('product')
df_dropped

        sales       price
region
East       42  612.015332
East       29  510.572273
East       68  642.106376
North      45  636.751785
North      24  679.160920
North      79  538.842805
South      61  501.890337
South      51  551.129229
South      56  579.716231

# Задание 11

In [ ]:
#Продемонстировать работу .merge.
np.random.seed(42)

n_orders = 100
order_ids = range(1001, 1001 + n_orders)
product_ids = np.random.randint(1, 6, size=n_orders)
quantities = np.random.randint(1, 20, size=n_orders)
dates = pd.date_range(start='2023-01-01', periods=n_orders, freq='D')


sales_df = pd.DataFrame({
    'order_id': order_ids,
    'product_id': product_ids,
    'quantity': quantities,
    'date': dates
})

sales_df

    order_id  product_id  quantity       date
0       1001           4         7 2023-01-01
1       1002           5         9 2023-01-02
2       1003           3         8 2023-01-03
3       1004           5        12 2023-01-04
4       1005           5         2 2023-01-05
..       ...         ...       ...        ...
95      1096           3         9 2023-04-06
96      1097           5         6 2023-04-07
97      1098           2        16 2023-04-08
98      1099           2         3 2023-04-09
99      1100           1         4 2023-04-10

[100 rows x 4 columns]

In [34]:
n_products = 6
product_ids = range(1, n_products + 1)
product_names = ['Laptop', 'Phone', 'Tablet', 'Monitor', 'Keyboard', 'Mouse']
prices = np.round(np.random.uniform(50, 1000, size=n_products), 2)
categories = np.random.choice(['Electronics', 'Accessories'], size=n_products)


products_df = pd.DataFrame({
    'product_id': product_ids,
    'product_name': product_names,
    'price': prices,
    'category': categories
})


products_df

   product_id product_name   price     category
0           1       Laptop   65.76  Accessories
1           2        Phone  536.49  Electronics
2           3       Tablet  265.17  Accessories
3           4      Monitor  662.91  Accessories
4           5     Keyboard  215.65  Electronics
5           6        Mouse  706.39  Electronics

In [35]:
inner_merge = sales_df.merge(products_df, on='product_id', how='inner')
print("\nInner Merge:")
inner_merge

Inner Merge:

,order_id,product_id,quantity,date,product_name,price,category
0,1001,4,7,2023-01-01,Monitor,662.91,Accessories
1,1002,5,9,2023-01-02,Keyboard,215.65,Electronics
2,1003,3,8,2023-01-03,Tablet,265.17,Accessories
3,1004,5,12,2023-01-04,Keyboard,215.65,Electronics
4,1005,5,2,2023-01-05,Keyboard,215.65,Electronics
...,...,...,...,...,...,...,...
95,1096,3,9,2023-04-06,Tablet,265.17,Accessories
96,1097,5,6,2023-04-07,Keyboard,215.65,Electronics
97,1098,2,16,2023-04-08,Phone,536.49,Electronics
98,1099,2,3,2023-04-09,Phone,536.49,Electronics
99,1100,1,4,2023-04-10,Laptop,65.76,Accessories

In [36]:
outer_merge = sales_df.merge(products_df, on='product_id', how='outer')
print("\nOuter Merge:")
outer_merge

Outer Merge:

,order_id,product_id,quantity,date,product_name,price,category
0,1019.0,1,1.0,2023-01-19,Laptop,65.76,Accessories
1,1024.0,1,15.0,2023-01-24,Laptop,65.76,Accessories
2,1025.0,1,15.0,2023-01-25,Laptop,65.76,Accessories
3,1034.0,1,13.0,2023-02-03,Laptop,65.76,Accessories
4,1039.0,1,7.0,2023-02-08,Laptop,65.76,Accessories
...,...,...,...,...,...,...,...
96,1081.0,5,19.0,2023-03-22,Keyboard,215.65,Electronics
97,1083.0,5,12.0,2023-03-24,Keyboard,215.65,Electronics
98,1084.0,5,6.0,2023-03-25,Keyboard,215.65,Electronics
99,1097.0,5,6.0,2023-04-07,Keyboard,215.65,Electronics
100,NaN,6,NaN,NaT,Mouse,706.39,Electronics

In [37]:
left_merge = sales_df.merge(products_df, on='product_id', how='left')
print("\nLeft Merge:")
left_merge

Left Merge:

,order_id,product_id,quantity,date,product_name,price,category
0,1001,4,7,2023-01-01,Monitor,662.91,Accessories
1,1002,5,9,2023-01-02,Keyboard,215.65,Electronics
2,1003,3,8,2023-01-03,Tablet,265.17,Accessories
3,1004,5,12,2023-01-04,Keyboard,215.65,Electronics
4,1005,5,2,2023-01-05,Keyboard,215.65,Electronics
...,...,...,...,...,...,...,...
95,1096,3,9,2023-04-06,Tablet,265.17,Accessories
96,1097,5,6,2023-04-07,Keyboard,215.65,Electronics
97,1098,2,16,2023-04-08,Phone,536.49,Electronics
98,1099,2,3,2023-04-09,Phone,536.49,Electronics
99,1100,1,4,2023-04-10,Laptop,65.76,Accessories

In [38]:
right_merge = sales_df.merge(products_df, on='product_id', how='right')
print("\nRight Merge:")
right_merge

Right Merge:

,order_id,product_id,quantity,date,product_name,price,category
0,1019.0,1,1.0,2023-01-19,Laptop,65.76,Accessories
1,1024.0,1,15.0,2023-01-24,Laptop,65.76,Accessories
2,1025.0,1,15.0,2023-01-25,Laptop,65.76,Accessories
3,1034.0,1,13.0,2023-02-03,Laptop,65.76,Accessories
4,1039.0,1,7.0,2023-02-08,Laptop,65.76,Accessories
...,...,...,...,...,...,...,...
96,1081.0,5,19.0,2023-03-22,Keyboard,215.65,Electronics
97,1083.0,5,12.0,2023-03-24,Keyboard,215.65,Electronics
98,1084.0,5,6.0,2023-03-25,Keyboard,215.65,Electronics
99,1097.0,5,6.0,2023-04-07,Keyboard,215.65,Electronics
100,NaN,6,NaN,NaT,Mouse,706.39,Electronics

# Задание 12

In [ ]:
#Продемонстрировать работу с .concat или append.
np.random.seed(42)

df1 = pd.DataFrame({
    'store': ['Store1'] * 3,
    'product': ['Laptop', 'Phone', 'Tablet'],
    'sales': np.random.randint(1, 10, size=3),
    'price': np.random.uniform(100, 1000, size=3)
})

df1

    store product  sales       price
0  Store1  Laptop      7  638.792636
1  Store1   Phone      4  240.416776
2  Store1  Tablet      8  240.395068

In [40]:

df2 = pd.DataFrame({
    'store': ['Store2'] * 3,
    'product': ['Monitor', 'Keyboard', 'Mouse'],
    'sales': np.random.randint(1, 10, size=3),
    'price': np.random.uniform(100, 1000, size=3)
})

df2

    store   product  sales       price
0  Store2   Monitor      8  228.580136
1  Store2  Keyboard      5  685.799626
2  Store2     Mouse      4  150.770421

In [41]:
vertical_concat = pd.concat([df1, df2], axis=0)
vertical_concat

    store   product  sales       price
0  Store1    Laptop      7  638.792636
1  Store1     Phone      4  240.416776
2  Store1    Tablet      8  240.395068
0  Store2   Monitor      8  228.580136
1  Store2  Keyboard      5  685.799626
2  Store2     Mouse      4  150.770421

In [42]:
horizontal_concat = pd.concat([df1, df2], axis=1)
horizontal_concat

    store product  sales       price   store   product  sales       price
0  Store1  Laptop      7  638.792636  Store2   Monitor      8  228.580136
1  Store1   Phone      4  240.416776  Store2  Keyboard      5  685.799626
2  Store1  Tablet      8  240.395068  Store2     Mouse      4  150.770421

In [43]:
vertical_concat_reset = pd.concat([df1, df2], axis=0).reset_index(drop=True)
vertical_concat_reset

    store   product  sales       price
0  Store1    Laptop      7  638.792636
1  Store1     Phone      4  240.416776
2  Store1    Tablet      8  240.395068
3  Store2   Monitor      8  228.580136
4  Store2  Keyboard      5  685.799626
5  Store2     Mouse      4  150.770421